### PR TITLE
Prepare v0.0.1

### PR DESCRIPTION
**Pull request by danielpetisme**
- [ ] Updating Readme
- [ ] Refactoring partials

### CODE REVIEW

**Comment by danielpetisme** [comment]
Hi @amanganiello90. 
I think the blueprint would deserve a first 0.x release. Would you mind to have a general review please.

My objective as this point is to be sure people know how to test the blueprint on a very first project.
Thank you

**Comment by amanganiello90** [comment]
Hi @danielpetisme, yes it is my pleasure! Thanks.

**Comment by amanganiello90** [comment]
Hi Daniel, the README.md seems ok, but I have not understand the second point about "Refactoring partials"

**Comment by danielpetisme** [comment]
Hello,
I massively rely on partials for generation. I preferred to have small pieces of EJS I include here and there. I wasn't fully satisfied with my structure so I refactored. Since it was quite impacting I preferred to do it before the 0.0.1 communication (which I hope will bring more people on the project).

**Comment by danielpetisme** [comment]
I will update the Readme because, as for now, the generation can't handle sonar so I prefer not mention it.

**Comment by amanganiello90** [comment]
ok! thanks

**Comment by danielpetisme** [comment]
I also have to generate the docker files (database etc)

**Comment by amanganiello90** [comment]
Great!

**Pull request closed without merging**
