### PR TITLE
Prettier

### PR DESCRIPTION
**Pull request by danielpetisme**
Run prettier java on the generated code.

### CODE REVIEW

**Comment by pascalgrimaud** [comment]
What you did, is nice but in complement, it would be cool to prettier directly the generated code, just after the template/transform.

See https://github.com/jhipster/generator-jhipster/pull/11371

In main generator, we can now use `--prettier-java` flag

**Comment by danielpetisme** [comment]
Hello @pascalgrimaud Il try
So far I do `jhipster --blueprints quarkus --prettier-java`
and it fails on
```
Error: No parser could be inferred for file: src/test/java/com/mycompany/myapp/ArchTest.java
```

I've added prettier and the java plugin in the blueprint package.json
```
    "dependencies": {
        "chalk": "2.4.2",
        "generator-jhipster": "6.8.0",
        "glob": "7.1.4",
        "lodash": "4.17.15",
        "mkdirp": "0.5.1",
        "prettier": "1.17.1",
        "prettier-plugin-java": "0.7.1"
    },
```

I'll continue investigating.

**Comment by danielpetisme** [comment]
@pascalgrimaud I found the issue.
https://github.com/jhipster/generator-jhipster/issues/11533

I'll way to have until get your feedback but since I think it will require a new JHipster release I may track your request on a dedicated issue and merge this one.

**Comment by pascalgrimaud** [comment]
@danielpetisme : I'd like to help but I'm noob in blueprint system lol. I was suggesting that because I think it will be simpler than formatting manually all `.java.ejs`

**Comment by danielpetisme** [comment]
It would perfectly make sense, and in fact it almost work OOTB... I'll merge this PR as-is and watch the issue I opened

**Pull request merged**
