### PR TITLE
User management

### PR DESCRIPTION
**Pull request by danielpetisme**
Provide a backend for the basic JHipster User management. Showcases:
- How to do integration tests
- Send mails and test it
- Qute templating

### CODE REVIEW

**Comment by amanganiello90** [comment]
OK, thanks, I will check better in these days.

**Comment by danielpetisme** [comment]
@amanganiello90 can I hope a review before the end of the week? I plan to do a demo and I would love having this PR merged.
Thanks

**Comment by amanganiello90** [comment]
> 
> 
> @amanganiello90 can I hope a review before the end of the week? I plan to do a demo and I would love having this PR merged.
> Thanks

Yes, I'm testing all well, for now any issues. :) .. tomorrow I will finish.

**Comment by danielpetisme** [comment]
Sweet!
Thanks!!

**Comment by amanganiello90** [comment]
HI @danielpetisme ,
I have tested and it is all ok. Only some suggestions:
1 - A clear explanation of usage in the README. It is mandatory to jave jdk 11?
2 - The generation is compliant only with jwt authentication. So for the user experience, it is better to customize the prompt avoiding to show the unused questions (oauth2 it is not implemented yet)

Congratulations for the good job!

**Comment by danielpetisme** [comment]
Thanks for the feedback.
Regarding the prompts I'm not sure how to do it.
I don't want to redefine the whole list of prompts only pick and update some of them, do you know if it's feasible?

**Comment by amanganiello90** [comment]
> Thanks for the feedback.
> Regarding the prompts I'm not sure how to do it.
> I don't want to redefine the whole list of prompts only pick and update some of them, do you know if it's feasible?

Yes it's possible to remove (in your case) a question from the prompt, without redefine it all.

**Comment by danielpetisme** [comment]
Any pointer, sample? I wasn't very motivated to re-do everything 😄

**Comment by amanganiello90** [comment]
> 
> 
> Any pointer, sample? I wasn't very motivated to re-do everything 😄

Today I try it with a PR... don't worry ;)

**Comment by danielpetisme** [comment]
Sweet.
Thanks

**Comment by danielpetisme** [comment]
Hello @amanganiello90 anyt news?
Can we consider to merge this PR and you'll improve the Readme/prompts later on via another PR?

**Comment by amanganiello90** [comment]
> 
> 
> Hello @amanganiello90 anyt news?
> Can we consider to merge this PR and you'll improve the Readme/prompts later on via another PR?

Hi @danielpetisme , I did a PR in the afternoon of 5 days ago:  https://github.com/jhipster/jhipster-quarkus/pull/29

**Comment by danielpetisme** [comment]
#shame I missed it.
So I merge this one and then yours?

**Comment by amanganiello90** [comment]
@danielpetisme perfect!

**Comment by danielpetisme** [comment]
Close #22

**Pull request merged**
